image:
  repository: docker.io/binhex/arch-qbittorrentvpn
  pullPolicy: IfNotPresent
  tag: 4.4.5-1-01@sha256:7d75da7e2d4f97105b00956f127d7d4e531ac81efe355173bdf0c2a7e5740c86

securityContext:
  readOnlyRootFilesystem: false

env:
  VPN_ENABLED: yes
  VPN_PROV: pia
  VPN_CLIENT: wireguard
  STRICT_PORT_FORWARD: yes
  ENABLE_PRIVOXY: yes
  LAN_NETWORK: 192.168.1.0/24

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        targetPort: 6881

  torrentudp:
    enabled: true
    ports:
      torrentudp:
        enabled: true
        port: 6881
        targetPort: 6881
        protocol: UDP

  privoxy:
    ports:
      privoxy:
        enabled: true
        port: 8118
        targetPort: 8118
        protocol: HTTP

persistence:
  config:
    enabled: true
    mountPath: "/config"
  
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true